name: Pipeline base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'poetry'
    - name: Install Qt6
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version: 6.6.1
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Generate docs
      run: |
        make docs-all
