name: Pipeline base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.0"
        cache: 'poetry'
    - name: Install Qt6
      run: |
        sudo apt-get update
        sudo apt-get install qt6-base-dev qt6-base-dev-tools
    - name: Install python dependencies
      run: poetry install
    - run: apt list | grep installed | grep qt6
    - name: Generate docs
      run: |
        make docs-all
