name: PR Check

on:
  workflow_call:
    inputs:
      export_doc:
        required: false
        type: boolean
        default: true
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-22.04

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.0"
        cache: 'poetry'
    - name: Install Python dependencies
      run: poetry install
    - name: Install Qt6
      run: |
        sudo apt-get update
        sudo apt-get install qt6-base-dev
    - name: Test run
      run: poetry run pytest -s --no-qt-log test_plot_widget.py
      env:
        QT_QPA_PLATFORM: "offscreen"

  formatting:

    runs-on: ubuntu-22.04

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.0"
        cache: 'poetry'
    - name: Install Python dependencies
      run: poetry install
    - name: Test run
      run: poetry run black .

  doc_gen:

      runs-on: ubuntu-22.04

      needs: test

      steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.11.0
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.0"
          cache: 'poetry'
      - name: Install Python dependencies
        run: poetry install
      - name: Install Qt6
        run: |
          sudo apt-get update
          sudo apt-get install qt6-base-dev
      - name: Generate Docs
        run: make docs-all
        env:
          QT_QPA_PLATFORM: "offscreen"
      - name: Export Docs
        if: ${{ inputs.export_doc }}
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            docs/appmap.yml
            docs/_build

